### ISSUE TITLE
Base64 Decode not working

### ISSUE THREAD

**Issue by simonhamp** [euphwes/base-encoder#1]
I'm trying to decode some binary data that has been Base64 encoded. I highlight the entire Base64 hash and try to run the decoder, but it fails with a message in the status bar: "1 failed item"

Do you know what might be failing?

I'm on macOS Sierra 10.12.3 with ST3 Build 3126.

**Comment by euphwes** [comment]
I'm not sure offhand what might be the problem... Base64-encoded values sometimes have trailing padding of 1 or 2 equals (=) signs to make the string the correct length. Is it possibly your encoded item is missing some padding?

Try manually adding 1 or 2 equals signs to the end of your Base64-encoded string, highlighting again, and running the decode.

You also said your data was binary data that has been Base64 encoded... when I wrote this little utility plugin, I mostly intended it to be used to encode and decode strings which were Base64 encoded. When  the utility decodes Base64-encoded values, it attempts to interpret the output bytes as a UTF-8 string. If it cannot be interpreted as a UTF-8 string, the decode will fail. That sounds like that's probably what's happening for you.

**Comment by simonhamp** [comment]
Thanks for the quick response 👍 

Yeh the padding is there correctly. So yeh it looks like the attempt to interpret as a UTF-8 string is definitely the problem.

Is there a way for me to stop that step from happening and just output the bytes as hex pairs?

**Comment by euphwes** [comment]
Not at the moment, but I could certainly look into that as an option! I think it would be a fairly small addition. I can look at implementing that in the next couple days, and publishing an update to this plugin. I'll keep this issue open until I implement that, and then comment here after I publish and close the issue, so you can see it.

**Comment by simonhamp** [comment]
I think that would be really useful for my case.

For now I have used an alternative method, but it would be very handy to have that available in Sublime so I don't need to run the encoded data through a separate tool 😃
